import { z } from 'zod';
declare const EnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    BOT_TOKEN: z.ZodString;
    BOT_USERNAME: z.ZodDefault<z.ZodString>;
    BOT_NAME: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    DB_HOST: z.ZodDefault<z.ZodString>;
    DB_PORT: z.ZodDefault<z.ZodNumber>;
    DB_NAME: z.ZodDefault<z.ZodString>;
    DB_USER: z.ZodDefault<z.ZodString>;
    DB_PASSWORD: z.ZodDefault<z.ZodString>;
    DB_SSL: z.ZodDefault<z.ZodBoolean>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    REDIS_PASSWORD: z.ZodDefault<z.ZodString>;
    BASE_URL: z.ZodDefault<z.ZodString>;
    WEB_PORT: z.ZodDefault<z.ZodNumber>;
    SESSION_SECRET: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodDefault<z.ZodString>;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodOptional<z.ZodString>;
    HUGGINGFACE_API_KEY: z.ZodOptional<z.ZodString>;
    OPENROUTER_API_KEY: z.ZodOptional<z.ZodString>;
    COINGECKO_API_KEY: z.ZodOptional<z.ZodString>;
    EXCHANGE_RATE_API_KEY: z.ZodOptional<z.ZodString>;
    OPENEXCHANGE_API_KEY: z.ZodOptional<z.ZodString>;
    MT_PROTO_API_ID: z.ZodOptional<z.ZodNumber>;
    MT_PROTO_API_HASH: z.ZodOptional<z.ZodString>;
    MT_PROTO_PHONE: z.ZodOptional<z.ZodString>;
    MT_PROTO_SESSION_STRING: z.ZodOptional<z.ZodString>;
    KAVENEGAR_API_KEY: z.ZodOptional<z.ZodString>;
    KAVENEGAR_SENDER: z.ZodOptional<z.ZodString>;
    MIXPANEL_TOKEN: z.ZodOptional<z.ZodString>;
    POSTHOG_API_KEY: z.ZodOptional<z.ZodString>;
    DOCKER_REGISTRY: z.ZodDefault<z.ZodString>;
    DOCKER_IMAGE_NAME: z.ZodDefault<z.ZodString>;
    DOCKER_TAG: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    BOT_TOKEN: string;
    BOT_USERNAME: string;
    BOT_NAME: string;
    DATABASE_URL: string;
    DB_HOST: string;
    DB_PORT: number;
    DB_NAME: string;
    DB_USER: string;
    DB_PASSWORD: string;
    DB_SSL: boolean;
    REDIS_URL: string;
    REDIS_PASSWORD: string;
    BASE_URL: string;
    WEB_PORT: number;
    SESSION_SECRET: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    DOCKER_REGISTRY: string;
    DOCKER_IMAGE_NAME: string;
    DOCKER_TAG: string;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    HUGGINGFACE_API_KEY?: string | undefined;
    OPENROUTER_API_KEY?: string | undefined;
    COINGECKO_API_KEY?: string | undefined;
    EXCHANGE_RATE_API_KEY?: string | undefined;
    OPENEXCHANGE_API_KEY?: string | undefined;
    MT_PROTO_API_ID?: number | undefined;
    MT_PROTO_API_HASH?: string | undefined;
    MT_PROTO_PHONE?: string | undefined;
    MT_PROTO_SESSION_STRING?: string | undefined;
    KAVENEGAR_API_KEY?: string | undefined;
    KAVENEGAR_SENDER?: string | undefined;
    MIXPANEL_TOKEN?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
}, {
    BOT_TOKEN: string;
    DATABASE_URL: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    PORT?: number | undefined;
    BOT_USERNAME?: string | undefined;
    BOT_NAME?: string | undefined;
    DB_HOST?: string | undefined;
    DB_PORT?: number | undefined;
    DB_NAME?: string | undefined;
    DB_USER?: string | undefined;
    DB_PASSWORD?: string | undefined;
    DB_SSL?: boolean | undefined;
    REDIS_URL?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    BASE_URL?: string | undefined;
    WEB_PORT?: number | undefined;
    SESSION_SECRET?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    HUGGINGFACE_API_KEY?: string | undefined;
    OPENROUTER_API_KEY?: string | undefined;
    COINGECKO_API_KEY?: string | undefined;
    EXCHANGE_RATE_API_KEY?: string | undefined;
    OPENEXCHANGE_API_KEY?: string | undefined;
    MT_PROTO_API_ID?: number | undefined;
    MT_PROTO_API_HASH?: string | undefined;
    MT_PROTO_PHONE?: string | undefined;
    MT_PROTO_SESSION_STRING?: string | undefined;
    KAVENEGAR_API_KEY?: string | undefined;
    KAVENEGAR_SENDER?: string | undefined;
    MIXPANEL_TOKEN?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
    DOCKER_REGISTRY?: string | undefined;
    DOCKER_IMAGE_NAME?: string | undefined;
    DOCKER_TAG?: string | undefined;
}>;
export type Env = z.infer<typeof EnvSchema>;
export declare class ConfigError extends Error {
    constructor(message: string);
}
export declare function loadConfig(): Env;
export declare function getConfig(): Env;
export declare function isDevelopment(): boolean;
export declare function isProduction(): boolean;
export declare function isTest(): boolean;
export {};
//# sourceMappingURL=config.d.ts.map